### ISSUE TITLE
autoproj-1.13.1: current_import_state': undefined method `show'

### ISSUE THREAD

**Issue by D-Alex** [rock-core/autobuild#20]
calling autoproj update results in the following error message:

autoproj-1.13.1/lib/autoproj/ops/snapshot.rb:169:in `current_import_state': undefined method `show' for nil:NilClass (NoMethodError)

I looked into the code and I think it cannot be assumed that main.importer is returning an object. 

The vhs which has no importer is (the git is a clone from another git on the hard disk):
local:/var/lib/jenkins/workspace/ropencv_gem/dev/autoproj

**Comment by D-Alex** [comment]
same propblem here:
gems/autoproj-1.13.1/lib/autoproj/ops/snapshot.rb:191:in `save_import_state': undefined method `git_dir' for nil:NilClass (NoMethodError)

**Comment by D-Alex** [comment]
move to autoproj
